version: "3.8"

services:
  proxy:
    image: nginx:1.13-alpine-perl
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - shared:/var/run/nginx
      - static:/app/staticfiles
    ports:
      - 80:80
    networks:
      - wimpy_wimpy-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "gunicorn wimpy.config.wsgi --bind unix:/var/run/nginx/wsgi.sock"
    environment:
      DEFAULT_DB_BACKEND: 'django.db.backends.mysql'
      DEFAULT_DB_HOST: 'wimpy_mysql_1'
      DEFAULT_DB_NAME: 'wimpy'
      DEFAULT_DB_USERNAME: 'root'
      DEFAULT_DB_PASSWORD: 'root'
      DEFAULT_CACHE_BACKEND: 'django_redis.cache.RedisCache'
      DEFAULT_CACHE_LOCATION: 'redis://wimpy_redis_1:6379/1'
      DEFAULT_CACHE_CLIENT_CLASS: 'django_redis.client.DefaultClient'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka1:19092'
      ASYNC_EVENTS_ENABLED: 'true'
    volumes:
      - shared:/var/run/nginx
      - static:/app/staticfiles
    networks:
      - wimpy_wimpy-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python3 manage.py consumer"
    environment:
      DEFAULT_DB_BACKEND: 'django.db.backends.mysql'
      DEFAULT_DB_HOST: 'wimpy_mysql_1'
      DEFAULT_DB_NAME: 'wimpy'
      DEFAULT_DB_USERNAME: 'root'
      DEFAULT_DB_PASSWORD: 'root'
      DEFAULT_CACHE_BACKEND: 'django_redis.cache.RedisCache'
      DEFAULT_CACHE_LOCATION: 'redis://wimpy_redis_1:6379/1'
      DEFAULT_CACHE_CLIENT_CLASS: 'django_redis.client.DefaultClient'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka1:19092'
      ASYNC_EVENTS_ENABLED: 'true'
    networks:
      - wimpy_wimpy-network

networks:
  wimpy_wimpy-network:
    external: true

volumes:
  shared:
  static:
