version: 2.1

jobs:
  test:
    working_directory: ~/circleci-wimpy
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - run: sudo apt install libmariadb-dev
      - run: pip install -r requirements/test.txt
      - run: pytest
      - run: coveralls

workflows:
  build_and_test:
    jobs:
      - test
